package foodAdditives.app;

import java.util.ArrayList;

public class AdditivesRepository {

	private ArrayList<Additive> allAdditives;
	
	public AdditivesRepository()
	{
		allAdditives = new ArrayList<Additive>();
		
		// populate additives
		allAdditives.add(new Additive("100", "כורכומין, כורכום", Safety.Safe,"צבע מאכל (צהוב - כתום)",""));
		allAdditives.add(new Additive("101", "ריבופלאבין (ויטמין B2), בעבר כונה ויטמין G", Safety.Safe,"צבע מאכל צהוב- כתום",""));
		allAdditives.add(new Additive("101a", "ריבופלאבין-5-פוספט", Safety.Safe,"צבע מאכל צהוב- כתום",""));
		allAdditives.add(new Additive("102", "טרטרזין (FD&C צהוב 5)", Safety.Forbidden,"צבע מאכל צהוב","נאסר לשימוש בארצות הברית, בריטניה, נורבגיה ואוסטריה."));
		allAdditives.add(new Additive("103", "קריזואין רסוריצנול (Chrysoine resorcinol)", Safety.Forbidden,"צבע מאכל זהוב","נאסר לשימוש בארצות הברית."));
		allAdditives.add(new Additive("104", "קווינולין צהוב", Safety.Forbidden,"צבע מאכל צהוב-ירוק","בבריטניה הומלץ שלא להשתמש בו, נאסר לשימוש בארצות הברית, אוסטרליה, נורבגיה ויפן."));
		allAdditives.add(new Additive("105", "צהוב מהיר AB ‏(Fast Yellow AB)", Safety.Forbidden,"צבע מאכל צהוב","אסור בשימוש בארצות הברית ובאירופה"));
		allAdditives.add(new Additive("106", "ריבופלבין-5-נתרן זרחתי (Riboflavin-5-Sodium Phosphate)", Safety.Safe,"צבע מאכל צהוב","מבוסס על עיבוד של ויטמין B2. נמצא בשימוש במזון תינוקות, ריבות ומוצרי חלב."));
		allAdditives.add(new Additive("107", "צהוב 2G", Safety.Forbidden,"צבע מאכל צהוב","צבע מאכל צהוב המבוסס על זפת פחם. נאסר לשימוש במספר רב של מדינות, וקיימת הצעה לאסור אותו לחלוטין בכל אירופה."));
		allAdditives.add(new Additive("110", "צהוב סנסט FCF (צהוב כתום S, FD&C צהוב 6)", Safety.Forbidden,"צבע מאכל צהוב-כתום","אסור בשימוש. צבע מאכל נפוץ במיוחד במספר רב של מאכלים ומסוכן לבריאות, המבוסס על זפת פחם."));
		allAdditives.add(new Additive("111", "כתום GGN", Safety.Forbidden,"צבע מאכל כתום","אסור לשימוש בארצות הברית ובאירופה."));
		allAdditives.add(new Additive("120", "כנימת קוצ'יניל, חומצה כרמינית (אדום טבעי 4)", Safety.Forbidden,"צבע מאכל אדום","צבע מאכל המופק ממין של חרק."));
		allAdditives.add(new Additive("121", "אדום תפוז 2", Safety.Forbidden,"צבע מאכל אדום כהה","אסור בשימוש"));
		allAdditives.add(new Additive("122", "אזורובין (קרמואיזין)", Safety.Suspicious,"צבע מאכל אדום - חום","נאסר לשימוש בקנדה, יפן, שבדיה וארצות הברית."));
		allAdditives.add(new Additive("123", "אמרנת (FD&C אדום 2)", Safety.Forbidden,"צבע מאכל אדום - כהה","נאסר לשימוש בארצות הברית ונורבגיה."));
		allAdditives.add(new Additive("124", "Ponceau 4R (קוצ'יניל אדום A, שני בוהק 4R)", Safety.Forbidden,"צבע מאכל אדום","נאסר לשימוש בארצות הברית ונורבגיה."));
		allAdditives.add(new Additive("125", "Ponceau SX, סגול GN", Safety.Forbidden,"צבע מאכל אדום",""));
		allAdditives.add(new Additive("126", "Ponceau 6R", Safety.Forbidden,"צבע מאכל אדום",""));
		allAdditives.add(new Additive("127", "אריתרוזין (FD&C אדום 3)", Safety.Forbidden,"צבע מאכל אדום","צבע מאכל אדום-ורוד המבוסס על זפת פחם. נאסר לשימוש בנורבגיה וארצות הברית."));
		allAdditives.add(new Additive("128", "אדום 2G", Safety.Forbidden,"צבע מאכל אדום","נאסר לשימוש במספר רב של מדינות ובהן ישראל. יש חשד שמפריע ליצירת ההמוגלובין בדם."));
		allAdditives.add(new Additive("129", "אדום אלורה AC ‏(FD&C אדום 40)", Safety.Forbidden,"צבע מאכל אדום","אסור בשימוש"));
		allAdditives.add(new Additive("130", "אינדנתרין כחול RS", Safety.Forbidden,"צבע מאכל כחול",""));
		allAdditives.add(new Additive("131", "פטנט כחול V", Safety.Forbidden,"צבע מאכל כחול כהה","אסור בשימוש"));
		allAdditives.add(new Additive("132", "דיו אינדגו, FD&C כחול 2", Safety.Safe,"צבע מאכל אינדגו","על בסיס זפת פחם. נאסר לשימוש בנורבגיה."));
		allAdditives.add(new Additive("133", "כחול בוהק FCF ‏(FD&C כחול 1)", Safety.Forbidden,"צבע מאכל כחול-אדום","צבע בו משתמשים לעתים קרובות בשילוב עם טרטזין כדי לקבל צבע ירוק. נאסר לשימוש בארגנטינה, בולגריה, צ'כיה, צרפת, איטליה, טורקיה ומספר מדינות נוספות."));
		allAdditives.add(new Additive("140", "כלורופילים וכלורפילינים: (i) כלורפילים (ii) כלורפילינים", Safety.Safe,"צבע מאכל ירוק",""));
		allAdditives.add(new Additive("141", "תרכובות נחושת של כלורופילים וכלורפילינים (i) תרכובות נחושת של כלורפילים (ii) תרכובות נחושת של כלורפילינים", Safety.Suspicious,"צבע מאכל ירוק",""));
		allAdditives.add(new Additive("142", "ירוק S", Safety.Forbidden,"צבע מאכל ירוק","נאסר לשימוש בקנדה, פינלנד, יפן, נורבגיה, שבדיה וארצות הברית."));
		allAdditives.add(new Additive("143", "ירוק מהיר FCF (FD&C ירוק 3)", Safety.Safe,"צבע מאכל ירוק-כחול",""));
		allAdditives.add(new Additive("150a", "קרמל", Safety.Safe,"צבע מאכל","אחד מצבעי המאכל הנפוצים ביותר בשימוש."));
		allAdditives.add(new Additive("150b", "קרמל סולפיט", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("150c", "קרמל אמוניה", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("150d", "קרמל סולפיט אמוניה", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("151", "שחור PN, שחור בוהק BN", Safety.Suspicious,"צבע מאכל","צבע מאכל סינתטי שחור-ארגמן על בסיס זפת פחם. נאסר לשימוש בקנדה, פינלנד, יפן, נורבגיה וארצות הברית."));
		allAdditives.add(new Additive("152", "שחור 7984", Safety.Forbidden,"צבע מאכל",""));
		allAdditives.add(new Additive("153", "פחמן שחור", Safety.Suspicious,"צבע מאכל שחור","נאסר לשימוש בארצות הברית. חשוד כמסרטן."));
		allAdditives.add(new Additive("154", "חום FK (חום קיפר)", Safety.Safe,"צבע מאכל חום","נאסר לשימוש בהרבה מאוד מדינות כולל כמעט כל מדינות אירופה, קנדה וארצות הברית."));
		allAdditives.add(new Additive("155", "חום HT (חום שוקולד HT)", Safety.Safe,"צבע מאכל חום","על בסיס זפת פחם. נאסר לשימוש במדינות רבות."));
		allAdditives.add(new Additive("160a", "אלפא-קרוטן, בטא-קרוטן, גמא-קרוטן", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("160b", "אנאטו, ביקסין, נורביקסין", Safety.Forbidden,"צבע מאכל","אסור בשימוש במזונות מסוימים[1]."));
		allAdditives.add(new Additive("160c", "תמצית פפריקה, קפסנתין, קפסורובין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("160d", "ליקופן", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("160e", "אפוקארטנאל (חומצה בטה-אפו-8-קרונטנית Beta-apo-8'-carotenal) ‏ (C 30)", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("160f", "אתיל אסטרי של חומצה בטה-אפו-8-קרונטנית (Ethyl ester of beta-apo-8'-carotenic acid) ‏ (C 30)", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161a", "פלבוקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161b", "לוטאין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161c", "קריפטוקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161d", "רוביקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161e", "ויולקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161f", "רודוקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161g", "קנתקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161h", "זיאקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161i", "סיטרנקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("161j", "אסטרקסנתין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("162", "אדום סלק, בטנין", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("163", "אנתוציאנינים", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("170", "סידן פחמתי, גיר", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("171", "דו תחמוצת הטיטניום (טיטניום דו תחמוצתי)", Safety.Suspicious,"צבע מאכל לבן","נאסר לשימוש בגרמניה."));
		allAdditives.add(new Additive("172", "תחמוצות ברזל והידרוקסידים", Safety.Suspicious,"צבע מאכל","נאסר לשימוש בגרמניה."));
		allAdditives.add(new Additive("173", "אלומיניום", Safety.Forbidden,"צבע מאכל","אסור בשימוש"));
		allAdditives.add(new Additive("174", "כסף", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("175", "זהב", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("180", "פיגמנט רובין, ליתול רובין BK", Safety.Forbidden,"צבע מאכל","אסור בשימוש"));
		allAdditives.add(new Additive("181", "טאנין", Safety.Forbidden,"צבע מאכל",""));
		allAdditives.add(new Additive("182", "אורצאין, Orchil", Safety.Forbidden,"צבע מאכל",""));
		allAdditives.add(new Additive("200", "חומצה סורבית", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("201", "נתרן סורבי", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("202", "אשלגן סורבי", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("203", "סידן סורבי", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("209", "הפטיל הידרובנזואיט (Heptyl p-hydroxybenzoate)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("210", "חומצה בנזואית", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("211", "סודיום בנזואט (נתרן בנזואט)", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("212", "אשלגן בנזואט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("213", "סידן בנזואט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("214", "אתילפרבן (ethyl para-hydroxybenzoate)", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("215", "נתרן אתילפרבן (Sodium ethyl para-hydroxybenzoate)", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("216", "פרופילפרבן (propyl para-hydroxybenzoate)", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("217", "נתרן פרופילפרבן (Sodium propyl para-hydroxybenzoate)", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("218", "מתילפרבן (methyl para-hydroxybenzoate)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("219", "נתרן מתילפרבן (Sodium methyl para-hydroxybenzoate)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("220", "גופרית דו-חמצנית", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("221", "נתרן סולפיט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("222", "נתרן ביסולפיט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("223", "נתרן מטביסולפיט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("224", "אשלגן מטביסולפיט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("225", "אשלגן סולפיט", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("226", "סידן סולפיט", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("227", "סידן ביסולפיט", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("228", "אשלגן ביסולפיט", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("230", "ביפניל, דיפניל", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("231", "אורתופניל פנול", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("232", "נתרן אורתופניל פנול", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("233", "תיאבנדזול", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("234", "ניסין", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("235", "נטמיצין, פימרצין", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("236", "חומצה פורמית", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("237", "נתרן פורמט (פורמט נתרן)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("238", "סידן פורמט", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("239", "הקסמין (הקסמתילן טטרמין)", Safety.Forbidden,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("240", "פורמאלדהיד (פורמלין)", Safety.Suspicious,"חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("242", "דימתיל קרבונאט", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("249", "אשלגן חנקיתי", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("250", "נתרן חנקיתי", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("251", "נתרן חנקתי", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("252", "אשלגן חנקתי (סלפטר)", Safety.Forbidden,"חומר משמר",""));
		allAdditives.add(new Additive("260", "חומצה אצטית (חומצת חומץ)", Safety.Safe,"חומר משמר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("261", "אשלגן אצטט", Safety.Safe,"חומר משמר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("262", "נתרן אצטטים (i) סודיום אצטט (ii) סודיום דיאצטט", Safety.Safe,"חומר משמר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("263", "סידן אצטט", Safety.Safe,"חומר משמר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("264", "אמוניה אצטט", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("265", "חומצה דיהידרואצטית", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("266", "נתרן דיהידרואצטי", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("270", "חומצה לקטית", Safety.Safe,"חומר משמר, חומר נוגד חמצון",""));
		allAdditives.add(new Additive("280", "חומצה פרופיונית", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("281", "נתרן פרופיוני", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("282", "סידן פרופיוני", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("283", "אשלגן פרופיוני", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("284", "חומצה בורית (חומצת בור)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("285", "נתרן סטאבוראט (בוראקס)", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("290", "פחמן דו-חמצני", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("296", "חומצה מאלית", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("297", "חומצה פומרית", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("300", "חומצה אסקורבית (ויטמין C)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("301", "נתרן אסקורבי", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("302", "קלציום אסקורבט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("303", "אשלגן אסקורבי", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("304", "אסקורביל פלמיטאט (אסטר של ויטמין C מסיס שומן)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("305", "אסקורביל צטרט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("306", "טוקופרול (ויטמין E טבעי)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("307", "אלפא-טוקופרול (ויטמין E סינתטי)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("308", "גמא-טוקופרול (ויטמין E סינתטי)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("309", "דלתא-טוקופרול (ויטמין E סינתטי)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("310", "פרופיל גאלאט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("311", "אוקטיל גאלאט", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("312", "דודקיל גאלאט", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("313", "אתיל גאלאט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("314", "שרף גואיאקום", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("315", "חומצה אריתורבית", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("316", "נתרן אריתורבי", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("317", "חומצה אריתורבינית", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("318", "נתרן אריתורביני", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("319", "tert-Butylhydroquinone‏ (TBHQ)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("320", "בוטיל הידרוקסיאניסול (BHA)", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("321", "בוטיל הידרוקסיטולני (BHT)", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("322", "לציטין", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("324", "אתוקסיקווין", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("325", "נתרן לקטאט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("326", "אשלגן לקטאט", Safety.Safe,"חומר מווסת חומציות, חומר נוגד חמצון",""));
		allAdditives.add(new Additive("327", "סידן לקטאט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("328", "אמוניום לקטאט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("329", "מגנזיום לקטאט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("330", "חומצה ציטרית", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("331", "נתרן ציטראטים (i) מונוסודיום ציטראט (ii) דיסודיום ציטראט (iii) נתרן ציטראט (טריסודיום ציטראט)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("332", "אשלגן ציטראטים (i) מונואשלגן ציטראט (ii) אשלגן ציטראט (תלת-אשלגן ציטראט)", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("333", "סידן ציטראטים (i) מונו-סידן ציטראט (ii) דו-סודיום ציטראט (iii) סידן ציטראט (טריסודיום ציטראט)", Safety.Safe,"חומר מווסת חומציות, חומר מייצב (מגביר חוזק), תצבית",""));
		allAdditives.add(new Additive("334", "חומצה טרטרית (L(+)-)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("335", "נתרן טרטרטים (i) מונוסודיום טרטרט (ii), דיסודיום טרטרט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("336", "אשלגן טרטרטים (i) מונואשלגן טרטרט (קרם טרטר) (ii) די-אשלגן טרטרט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("337", "נתרת אשלגן טרטרט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("338", "חומצה זרחתית", Safety.Forbidden,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("339", "נתרנים זרחתיים (i) חד נתרן זרחתי (ii) דו נתרן זרחתי (iii) תלת נתרן זרחתי", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("340", "אשלגנים זרחתיים (i) חד אשלגן זרחתי (ii) דו אשלגן זרחתי (iii) תלת אשלגן זרחתי", Safety.Forbidden,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("341", "סידנים זרחתיים (i) חד סידן זרחתי (ii) דו סידן זרחתי (iii) תלת סידן זרחתי", Safety.Forbidden,"חומר מונע התגיישות, חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("342", "אמוניום זרחתי: (i) חד אמוניום זרחתי (ii) דיאמוניום זרחתי", Safety.Safe,"",""));
		allAdditives.add(new Additive("343", "מגנזיום זרחתי: (i) חד מגנזיום זרחתי (ii) דו מגנזיום זרחתי", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("344", "לציטין ציטראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("345", "מגנזיום ציטראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("349", "אמוניום מאלאט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("350", "נתרן מאלאט (i) נתרן מאלאט (ii) נתרן מאלאט מימני", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("351", "אשלגן מאלאט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("352", "סידן מאלאט (i) סידן מאלאט (ii) סידן מאלאט מימני", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("353", "חומצה מטטרטרית", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("354", "סידן טרטרי", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("355", "חומצה אדיפית", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("356", "נתרן אדיפי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("357", "אשלגן אדיפטי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("359", "אמוניום אדיפטי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("363", "חומצה סוקסינית", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("365", "נתרן פומאראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("366", "אשלגן פומאראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("367", "סידן פומאראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("368", "אמוניום פומאראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("370", "1,4-הפטונולקטון", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("375", "ניאצין (ויטמין B3), וניקוטינאמיד", Safety.Safe,"חומר משמר צבע",""));
		allAdditives.add(new Additive("380", "תלת-אמוניום ציטראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("381", "אמוניום ציטראט הברזל", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("383", "סידן גליצרילזרחת", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("384", "איזופרופיל ציטראט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("385", "סידן דו זרחתי אתניל דיאמין טטראקטאט", Safety.Safe,"תצבית",""));
		allAdditives.add(new Additive("386", "דו סידן אתילן דיאמין טטראקטאט", Safety.Safe,"תצבית",""));
		allAdditives.add(new Additive("387", "אוקסיסטירין", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("388", "חומצה תיאודיפרופיונית", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("389", "דילוריל תיאודיפרופיוני", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("390", "דיסטיריל תיאודיפרופיוני", Safety.Safe,"",""));
		allAdditives.add(new Additive("391", "חומצה פיטית", Safety.Safe,"",""));
		allAdditives.add(new Additive("399", "חומצה לקטוביונית", Safety.Safe,"",""));
		allAdditives.add(new Additive("400", "חומצת אלגין (חומצה אלגינית)", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("401", "נתרן אלגיני", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("402", "אשלגן אלגיני", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב, חומר מקריש",""));
		allAdditives.add(new Additive("403", "אמוניום אלגיני", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("404", "סידן אלגיני", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב, חומר מקריש",""));
		allAdditives.add(new Additive("405", "פרופאן-1,2-דיאול אלגיני", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("406", "אגר", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מקריש",""));
		allAdditives.add(new Additive("407", "קרגינן", Safety.Forbidden,"חומר מייצב, חומר מסמיך, חומר מתחלב, חומר מקריש",""));
		allAdditives.add(new Additive("407a", "אצת וקאמה מעובדת", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר מתחלב, חומר מקריש",""));
		allAdditives.add(new Additive("408", "גליקן שמרים", Safety.Safe,"",""));
		allAdditives.add(new Additive("409", "אראבינוגלקטאן", Safety.Safe,"",""));
		allAdditives.add(new Additive("410", "גומי חרוב", Safety.Safe,"חומר מתחלב, חומר מייצב (מגביר חוזק), חומר מקריש",""));
		allAdditives.add(new Additive("411", "גומי דגנים", Safety.Safe,"חומר מסמיך, חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("412", "גומי גואר", Safety.Safe,"חומר מסמיך, חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("413", "גומי קדד (גומי טרגקנת, גומי טראגאקאנט)", Safety.Safe,"חומר מסמיך, חומר מייצב (מגביר חוזק), חומר מתחלב",""));
		allAdditives.add(new Additive("414", "גומי ערבי (גומי ערביקום)", Safety.Safe,"חומר מסמיך, חומר מייצב (מגביר חוזק), חומר מתחלב",""));
		allAdditives.add(new Additive("415", "גומי קסנטן", Safety.Safe,"חומר מייצב, חומר מסמיך",""));
		allAdditives.add(new Additive("416", "גומי קארייה", Safety.Safe,"חומר מתחלב, חומר מייצב, חומר מסמיך",""));
		allAdditives.add(new Additive("417", "גומי טארה", Safety.Safe,"חומר מייצב, חומר מסמיך",""));
		allAdditives.add(new Additive("418", "גומי גלאן", Safety.Safe,"חומר מתחלב, חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("419", "גומי ג'טי", Safety.Safe,"חומר מתחלב, חומר מייצב, חומר מסמיך",""));
		allAdditives.add(new Additive("420", "סורביטול (i) סורביטול (ii) סירופ סורביטול", Safety.Safe,"חומר הלחה, ממתיק, חומר מתחלב",""));
		allAdditives.add(new Additive("421", "מניטול", Safety.Safe,"ממתיק, חומר מונע התגיישות",""));
		allAdditives.add(new Additive("422", "גליצרול", Safety.Safe,"ממתיק, חומר מתחלב",""));
		allAdditives.add(new Additive("424", "Curdlan", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("425", "גומי קוניאק (i) גומי קוניאק (ii) קוניאק גלוקומאנאן", Safety.Forbidden,"חומר מתחלב","אסור בשימוש"));
		allAdditives.add(new Additive("426", "המיצלולוזת סויה", Safety.Safe,"",""));
		allAdditives.add(new Additive("429", "פפטונים", Safety.Safe,"",""));
		allAdditives.add(new Additive("430", "פוליוקסיתן (8) ציטראט", Safety.Safe,"חומר מייצב, חומר מתחלב",""));
		allAdditives.add(new Additive("431", "פוליוקסיתן (40) ציטראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("432", "פוליוקסיתן (20) סורביטאן מונולוראט (פוליסורבאט 20)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("433", "פוליוקסיתן (20) סורביטאן מונואולאט (פוליסורבאט 80)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("434", "פוליוקסיתן (20) סורביטאן מונופאליטאט (פוליסורבאט 40)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("435", "פוליוקסיתן (20) סורביטאן מונוצטיראט (פוליסורבאט 60)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("436", "פוליוקסיתן (20) סורביטאן טריצטיראט (פוליסורבאט 65)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("440", "פקטינים (i) פקטין (ii) נגזרות פקטין", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("441", "ג'לטין", Safety.Safe,"חומר מתחלב, חומר קרישה",""));
		allAdditives.add(new Additive("442", "אמוניום פוספאטידים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("443", "שמן צמחי ברומי", Safety.Safe,"",""));
		allAdditives.add(new Additive("444", "סוכרוז אצטט איסובוטיראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("445", "אסטר גליצורלי של שרף עצים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("446", "סוכיסטירין", Safety.Safe,"",""));
		allAdditives.add(new Additive("450", "דו זרחות (i) דו-נתרן דו-זרחתי (ii) תלת-נתרן דו-זרחתי (iii) טטרה-נתרן דו-זרחתי (iv) דו-אשלגן דו-זרחתי (v) טטרה-אשלגן דו-זרחתי (vi) דו-סידן דו-זרחתי (vii) סידן דו-מימן דו-זרחתי", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("451", "תלת זרחות (i) נתרן תלת-זרחתי (חמש-נתרן תלת-זרחתי) (ii) חמש-אשלגן תלת-זרחתי", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("452", "רב-זרחתו (i) נתרנים רב-זרחתיים (ii) אשלגנים רב זרחתיים (iii) נתרנים סידניים רב-זרחתיים (iv) סידנים רב- זרחתיים (v) אמוניומים רב-זרחתיים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("459", "בטא-ציקלודקסטרין", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("460", "תאית (צלולוזה) (i) תאית מיקרוקריסטלינית (ii) אבקת תאית", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("461", "מתיל תאית", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("462", "אתיל תאית", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("463", "הידרוקסיפרופיל תאית", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("464", "הידרוקסי פרופיל מתיל תאית (היפרומלוז)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("465", "אתיל מתיל תאית", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("466", "קרבוקסימתיל תאית", Safety.Forbidden,"חומר מתחלב",""));
		allAdditives.add(new Additive("467", "אתיל הידרוקיתיל תאית", Safety.Safe,"",""));
		allAdditives.add(new Additive("468", "נתרן קרבוקסימתיל תאית (קרוסקרמלוז)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("469", "קרבוקסימתילתאית שעבר הדירוליזה אזנימית", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("470", "מלחי חומצות שומן על בסיס אלומוניום, סידן, נתרן, אשלגן, ואמוניום", Safety.Safe,"",""));
		allAdditives.add(new Additive("470a", "מלחי אשלגן, נתרן וסידן של חומצות שומן", Safety.Safe,"חומר מונע התגיישות, חומר מתחלב",""));
		allAdditives.add(new Additive("470b", "מלחי חומצות שומן על בסיס מגנזיום", Safety.Safe,"חומר מונע התגיישות, חומר מתחלב",""));
		allAdditives.add(new Additive("471", "גלציריל מונוצטיראט, גליצריל דיצטיראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472a", "אסטרים של חומצה אצטית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472b", "אסטרים של חומצה לקטית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472c", "אסטרים של חומצה ציטרית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472d", "אסטרים של חומצה טרטרית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472e", "מונו ודי-אצטיל אסטרים של חומצה אצטית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472f", "אסטרים של תערובות של חומצה אצטית וחומצה טרטרית של מונו ודיגליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("472g", "מונוגליצרידים סוכינילאטים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("473", "אסטרים סוקרוזים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("474", "סוכרוגליצרידים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("475", "אסטרים פוליגליצרולים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("476", "פוליגליצרול פוליריצינולאט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("477", "אסטר פרופאן-1, 2-דיאול של חומצות שומן, אסטר פרופילן גליקול של חומצות שומן", Safety.Suspicious,"חומר מתחלב",""));
		allAdditives.add(new Additive("478", "אסטר לקטילי של חומצות שומן של גליקרון ופרופאן-1", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("479b", "שמן פולי סויה מחומצן בחום עם מונו ודו-גליצרידים של חומצות שומן", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("480", "דיוקטיל נתרן זרחן סוקרינאטי", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("481", "נתרן סטיריול-2-לקטילאט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("482", "סידן סטיריול-2-לקטילאט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("483", "סטיריל טרטראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("484", "סטיריל ציטראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("485", "נתרן סטיריאול פומאראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("486", "סידן צטיריאול פומאראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("487", "נתרן לורילסולפאט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("488", "אתוקסיל מונו ודו-גליצרידים", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("489", "מתיל גלוקוסיד - אסטר שמן קוקוס", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("490", "פרופאן-1,2-דיאול", Safety.Safe,"",""));
		allAdditives.add(new Additive("491", "סורביטן מונוסטיראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("492", "סורביטן תלת-סטיראט (סורביטן טריסטיראט)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("493", "סורביטן מונולוראט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("494", "סורביטן מונואוליט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("495", "סורביטן מונופאלמיטאט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("496", "סורביטן טריוליט", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("497", "פולימרים של פרוליוקסיפרופילן-פוליוקסיאתילן", Safety.Safe,"",""));
		allAdditives.add(new Additive("498", "פוליגליקרול חלקי של אסטרים של חומצות שומן עם שמן קיק", Safety.Safe,"",""));
		allAdditives.add(new Additive("499", "גומי קסייה", Safety.Safe,"",""));
		allAdditives.add(new Additive("500", "קרבונטים של נתרן (i) נתרן קרבונט (ii) נתרן ביקרבונט (נתרן מימן-קרבונט) (iii) נתרן ססקויקרבונט", Safety.Safe,"חומר מווסת חומציות, חומר התפחה",""));
		allAdditives.add(new Additive("501", "קרבונטים של אשלגן (i) אשלגן קרבונט (ii) אשלגן ביקרבונט (אשלגן מימן-קרבונט)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("503", "קרבונטים של אמוניום (i) אמוניום קרבונט (ii) אמוניום ביקרבונט (אמוניום מימן-קרבונט)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("504", "קרבונטים של מגנזיום (i) מגנזיום קרבונט (ii) מגנזיום ביקרבונט (מגנזיום מימן-קרבונט)", Safety.Safe,"חומר מווסת חומציות, חומר מונע התגיישות",""));
		allAdditives.add(new Additive("505", "סידריט", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("507", "חומצת מימן כלורי (חומצה הידרוכלורית, חומצת מלח)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("508", "אשלגן כלורי", Safety.Safe,"חומר טעם, חומר מקריש",""));
		allAdditives.add(new Additive("509", "סידן כלורי", Safety.Safe,"חומר מייצב (מגביר חוזק), תצבית",""));
		allAdditives.add(new Additive("510", "אמוניום כלורי", Safety.Safe,"חומר משפר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("511", "מגנזיום כלורי", Safety.Safe,"חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("512", "בדיל כלורי", Safety.Forbidden,"חומר נוגד חמצון","אסור בשימוש"));
		allAdditives.add(new Additive("513", "חומצה גופרתית", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("514", "נתרן גופרתי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("515", "אשלגן גופרתי", Safety.Safe,"",""));
		allAdditives.add(new Additive("516", "סידן גופרתי", Safety.Safe,"",""));
		allAdditives.add(new Additive("517", "אמוניום גופרתי", Safety.Safe,"חומר משפר",""));
		allAdditives.add(new Additive("518", "מגנזיום גופרתי (מלח אפסום)", Safety.Safe,"חומר מייצב (מגביר חוזק), חומר מווסת חומציות",""));
		allAdditives.add(new Additive("519", "נחושת (II) גופרתית", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("520", "אלומיניום גופרתי (אלומיניום סולפאט)", Safety.Safe,"חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("521", "אלומיניום נתרן גופרתי (אלומיניום נתרן סולפאט)", Safety.Safe,"חומר מייצב (מגביר חוזק)",""));
		allAdditives.add(new Additive("522", "אלומיניום אשלגן גופרתי (אלומיניום אשלגן סולפאט)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("523", "אלומיניום אמוניום גופרתי (אלומיניום אמוניום סולפאט)", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("524", "נתרן הידרוקסידי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("525", "אשלגן הידרוקסידי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("526", "סידן הידרוקסידי", Safety.Safe,"חומר מייצב (מגביר חוזק), חומר מווסת חומציות",""));
		allAdditives.add(new Additive("527", "אמוניום הידרוקסידי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("528", "מגנזיום הידרוקסידי", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("529", "סידן חמצני", Safety.Safe,"חומר משפר, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("530", "מגנזיום חמצני (מגנזיה)", Safety.Safe,"חומר מונע התגיישות, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("535", "נתרן פרוציאניד", Safety.Safe,"חומר מונע התגיישות, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("536", "אשלגן פרוציאניד", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("537", "פרוס הקסציאנומנגנט", Safety.Forbidden,"חומר מונע התגיישות","אסור בשימוש"));
		allAdditives.add(new Additive("538", "סידן פרוציאניד", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("539", "נתרן תיוסולפט", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("540", "דו-סידן דו-זרחתי", Safety.Safe,"חומר מתחלב, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("541", "נתרן אלומינים זרחתי (i) חומצי (ii) בסיסי", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("542", "סידן זרחתי", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("543", "סידן נתרן פוליפוספט (סידן נתרן רב-זרחתי)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("544", "סידן פוליפוספט (סידן רב-זרחתי)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("545", "אמוניום פוליפוספט (אמוניום רב-זרחתי)", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("550", "נתרן סיליקטים (i) נתרן סיליקט (ii) נתרן מטסיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("551", "צורן דו-חמצני (סיליקה)", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("552", "סידן סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("553a", "(i) מגנזיום סיליקט (ii) מגנזיום תלת-סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("553b", "טלק", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("554", "נתרן אלומיניום סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("555", "אשלגן אלומיניום סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("556", "סידן אלומיניום סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("557", "המימורפיט", Safety.Forbidden,"חומר מונע התגיישות","אסור בשימוש"));
		allAdditives.add(new Additive("558", "בנטוניט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("559", "אמוניום סיליקט (קאולין)", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("560", "אשלגן סיליקט", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("561", "ורמיקוליט", Safety.Safe,"",""));
		allAdditives.add(new Additive("562", "ספיוליט", Safety.Safe,"",""));
		allAdditives.add(new Additive("563", "חמר ספיוליטי", Safety.Safe,"",""));
		allAdditives.add(new Additive("565", "ליגנוסופלונאט", Safety.Safe,"",""));
		allAdditives.add(new Additive("566", "נטרוליט-פונוליט", Safety.Safe,"",""));
		allAdditives.add(new Additive("570", "חומצה סטארית", Safety.Safe,"חומר מונע התגיישות",""));
		allAdditives.add(new Additive("572", "מגנזיום סטארט, סידן סטארט", Safety.Safe,"חומר מונע התגיישות, חומר מתחלב",""));
		allAdditives.add(new Additive("574", "חומצה גלוקונית", Safety.Safe,"חומר מווסת חומציות",""));
		allAdditives.add(new Additive("575", "גלוקונו דלתא לקטון", Safety.Safe,"תצבית, חומר מווסת חומציות",""));
		allAdditives.add(new Additive("576", "נתרן גלוקונט", Safety.Safe,"תצבית",""));
		allAdditives.add(new Additive("577", "אשלגן גלוקונט", Safety.Safe,"תצבית",""));
		allAdditives.add(new Additive("578", "סידן גלוקונט", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("579", "ברזל גלוקונט", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("580", "מגנזיום גלוקונט", Safety.Safe,"",""));
		allAdditives.add(new Additive("585", "ברזל לקטט", Safety.Safe,"צבע מאכל",""));
		allAdditives.add(new Additive("586", "4-הקסילרסורקינול", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("598", "סידן אלומינט סינתטי", Safety.Safe,"",""));
		allAdditives.add(new Additive("599", "פרלייט", Safety.Safe,"",""));
		allAdditives.add(new Additive("620", "חומצה גלוטמית", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("621", "מונוסודיום גלוטמט (MSG)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("622", "מונופוטסיום גלוטמט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("623", "סידן דיגלוטומט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("624", "מונואמוניום גלוטמט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("625", "מגנזיום דיגלוטמט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("626", "גואנוסין חד זרחתי (חומצה גואנילית)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("627", "דו-נתרן גואנילט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("628", "דואשלגן גואניליט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("629", "נתרן גואנליט", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("630", "חומצה אינוצינית", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("631", "דו-נתרן אינוציני (דיסודיום אינוצינט)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("632", "דו-אשלגן אינוציני (דיפוטרסיום אינוצינט)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("633", "סידן אינוציני (קלציום אינוצינט)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("634", "Calcium 5'-ribonucleotide", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("635", "Disodium 5'-ribonucleotide", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("636", "מלטול", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("637", "אתיל מלטול", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("640", "גליצין ומלחי הנתרן שלו", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("641", "לאוצין (L-leucine)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("642", "ליזין", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("650", "אצטט האבץ", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("700", "בציטרצין", Safety.Safe,"",""));
		allAdditives.add(new Additive("701", "אנטיביוטיקה טטרציקלינית", Safety.Safe,"",""));
		allAdditives.add(new Additive("702", "Chlortetracycline", Safety.Safe,"",""));
		allAdditives.add(new Additive("703", "Oxytetracycline", Safety.Safe,"",""));
		allAdditives.add(new Additive("704", "Oleandomycin", Safety.Safe,"",""));
		allAdditives.add(new Additive("705", "פניצילין Penicillin-G-potassium", Safety.Safe,"",""));
		allAdditives.add(new Additive("706", "Penicillin-G-sodium", Safety.Safe,"",""));
		allAdditives.add(new Additive("707", "Penicillin-G-procaine", Safety.Safe,"",""));
		allAdditives.add(new Additive("708", "Penicillin-G-benzathyne", Safety.Safe,"",""));
		allAdditives.add(new Additive("710", "Spiramycin", Safety.Safe,"",""));
		allAdditives.add(new Additive("711", "Virginiamicin", Safety.Safe,"",""));
		allAdditives.add(new Additive("712", "Flavophospholipol", Safety.Safe,"",""));
		allAdditives.add(new Additive("713", "Tylosin", Safety.Safe,"",""));
		allAdditives.add(new Additive("714", "Monensin", Safety.Safe,"",""));
		allAdditives.add(new Additive("715", "Avoparcin", Safety.Safe,"",""));
		allAdditives.add(new Additive("716", "Salinomycin", Safety.Safe,"",""));
		allAdditives.add(new Additive("717", "Avilamycin", Safety.Safe,"",""));
		allAdditives.add(new Additive("900", "Dimethyl polysiloxane (חומר מונע קיצוץ)", Safety.Safe,"חומר מונע קיצוף",""));
		allAdditives.add(new Additive("901", "שעוות דבורים , צהובה ולבנה", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("902", "שעוות קנדלילה", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("903", "שעוות ברזיל", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("904", "שילק", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("905", "פרפין", Safety.Safe,"",""));
		allAdditives.add(new Additive("905a", "שמן מינרלי", Safety.Safe,"חומר מונע קיצוף",""));
		allAdditives.add(new Additive("905b", "פטרולאטום", Safety.Safe,"",""));
		allAdditives.add(new Additive("905c", "שעוות פרפין", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("906", "שרף לבנה רפואי", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("907", "פרפין", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("908", "שעוות שמן אורז", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("909", "שעוות ספרמצ'טי", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("910", "אסטר של שעווה", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("911", "אסטר ממטיל", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("912", "שעוות מונטאן", Safety.Forbidden,"חומר הזגה","אסור בשימוש"));
		allAdditives.add(new Additive("913", "לנולין (שומן צמר כבשים)", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("914", "שעוות תחמוצת פוליאתילן", Safety.Forbidden,"חומר הזגה","אסור בשימוש"));
		allAdditives.add(new Additive("915", "אסטר של שרף", Safety.Safe,"חומר הזגה",""));
		allAdditives.add(new Additive("916", "יודיד הסידן", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("917", "יודיד האשלגן", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("918", "תחמוצות חנקן", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("919", "תחמוצת חנקן כלורי", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("920", "ציסטאין (L-cysteine)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("921", "ציסטין (L-cystine)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("922", "אשלגן סולפטי", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("923", "אמוניום סולפטי", Safety.Forbidden,"חומר מחזק טעם","אסור בשימוש"));
		allAdditives.add(new Additive("924", "אשלגן ברומי", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("924b", "סידן ברומי", Safety.Forbidden,"חומר מחזק טעם","אסור בשימוש"));
		allAdditives.add(new Additive("925", "כלור", Safety.Forbidden,"חומר משמר, חומר הלבנת קמח, חומר מחזק טעם","אסור בשימוש"));
		allAdditives.add(new Additive("926", "דו תחמוצת הכלור (כלור דו-חמצני)", Safety.Forbidden,"חומר הלבנת קמח, חומר משמר","אסור בשימוש"));
		allAdditives.add(new Additive("927a", "אזודיקרבונמיד (Azodicarbonamide)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("927b", "שתנן (אוריאה)", Safety.Safe,"חומר מחזק טעם",""));
		allAdditives.add(new Additive("928", "על תחמוצת בנזואיל", Safety.Safe,"חומר הלבנת קמח",""));
		allAdditives.add(new Additive("929", "טריאצטון (על תחמוצת האצטון, אצטון על חמצני, אצטון פרוקסיד)", Safety.Forbidden,"","אסור בשימוש"));
		allAdditives.add(new Additive("930", "על תחמוצת הסידן (סידן פרוקסיד)", Safety.Safe,"חומר הלבנת קמח",""));
		allAdditives.add(new Additive("938", "ארגון", Safety.Safe,"גז אריזה",""));
		allAdditives.add(new Additive("939", "הליום", Safety.Safe,"גז אריזה",""));
		allAdditives.add(new Additive("940", "דיכלורודיפלואורומתאן", Safety.Safe,"גז אריזה",""));
		allAdditives.add(new Additive("941", "חנקן", Safety.Safe,"חומר הדף, גז אריזה",""));
		allAdditives.add(new Additive("942", "חמצן דו-חנקני (גז צחוק)", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("943a", "בוטאן", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("943b", "איזובוטאן", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("944", "פרופאן", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("945", "כלורופנטהפלורובוטאן", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("946", "אוקטפלורוציקלובוטאן", Safety.Safe,"חומר הדף",""));
		allAdditives.add(new Additive("948", "חמצן", Safety.Safe,"גז אריזה",""));
		allAdditives.add(new Additive("949", "מימן", Safety.Safe,"גז אריזה",""));
		allAdditives.add(new Additive("950", "אצסולפאם האשלגן (אצסולפאם K)", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("951", "אספרטם", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("952", "ציקלמט", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("953", "איסומלט, איסומלטיטול", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("954", "סכרין ומלחיו", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("955", "סוכלרוז (Trichlorogalactosucrose)", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("956", "אלטיטם", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("957", "תאומטין", Safety.Safe,"ממתיק, חומר מגביר טעם",""));
		allAdditives.add(new Additive("958", "גלצריזין", Safety.Safe,"ממתיק, חומר מגביר טעם",""));
		allAdditives.add(new Additive("959", "נאורספרידין דיהידרוצלקון (Neohesperidine dihydrochalcone)", Safety.Safe,"ממתיק, חומר מגביר טעם",""));
		allAdditives.add(new Additive("960", "סטוויאול גליקוסייד", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("961", "נאוטם", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("962", "מלח אספרטם-אקסולפם", Safety.Safe,"ממתיק, חומר מייצב",""));
		allAdditives.add(new Additive("965", "מלטיטול (i) מלטיטול (ii) סירופ מלטיטול (ממתיק)", Safety.Safe,"חומר הלחה, חומר מייצב",""));
		allAdditives.add(new Additive("966", "לקטיטול", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("967", "קסיליטול", Safety.Safe,"ממתיק",""));
		allAdditives.add(new Additive("968", "אריתריטול", Safety.Safe,"חומר הלחה",""));
		allAdditives.add(new Additive("999", "תמצית שרף קוויליה", Safety.Safe,"חומר מקציף",""));
		allAdditives.add(new Additive("1000", "חומצה כולית", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("1001", "מלחי כולין", Safety.Safe,"חומר מתחלב",""));
		allAdditives.add(new Additive("1100", "עמילאז", Safety.Safe,"חומר מייצב, חומר מחזק טעם",""));
		allAdditives.add(new Additive("1101", "פרוטאזים ((i)פרואטז, (ii)פאפאין, (iii)ברומלאין, (iv)פיקין)", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("1102", "חומצת גלוקוז", Safety.Safe,"חומר נוגד חמצון",""));
		allAdditives.add(new Additive("1103", "אינוורטאז", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("1104", "ליפאז", Safety.Safe,"",""));
		allAdditives.add(new Additive("1105", "ליזוזים", Safety.Safe,"חומר משמר",""));
		allAdditives.add(new Additive("1200", "פולדקסטרוז", Safety.Safe,"חומר מייצב, חומר מסמיך, חומר הלחה, חומר מוביל",""));
		allAdditives.add(new Additive("1201", "פוליווינילפירולידון (Polyvinylpyrrolidone)", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("1202", "פוליווינילפוליפירולידון (Polyvinylpolypyrrolidone)", Safety.Safe,"חומר מייצב",""));
		allAdditives.add(new Additive("1203", "אלכוהול פוליוויניל", Safety.Safe,"",""));
		allAdditives.add(new Additive("1204", "פולולאן (Pullulan)", Safety.Safe,"",""));
		allAdditives.add(new Additive("1400", "דקסטרין (עמילן קלוי)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1401", "עמילן מעובד (באמצעות חומצה)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1402", "עמילן מעובד אלקלי", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1403", "עמילן מולבן", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1404", "חומצת עמילן", Safety.Safe,"חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("1405", "עמילן מעובד בתוספת אנזימים", Safety.Safe,"",""));
		allAdditives.add(new Additive("1410", "עמילן מעובד (Monostarch phosphate)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1411", "עמילן מעובד (Distarch glycerol)", Safety.Safe,"חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("1412", "עמילן מעובד (Distarch phosphate עם sodium trimetasphosphate או עם phosphorus oxychloride)", Safety.Safe,"חומר מסמיך או חומר מייצב",""));
		allAdditives.add(new Additive("1413", "עמילן מעובד (Phosphated distarch phosphate)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1414", "עמילן מעובד (Acetylated distarch phosphate)", Safety.Safe,"חומר מסמיך, חומר מתחלב",""));
		allAdditives.add(new Additive("1420", "עמילן מעובד (Starch acetate esterified עם acetic anhydride)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1421", "עמילן מעובד (Starch acetate esterified עם vinyl acetate)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1422", "עמילן מעובד (Acetylated Distarch Adipate)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1423", "עמילן מעובד (Acetylated distarch glycerol)", Safety.Safe,"חומר מסמיך",""));
		allAdditives.add(new Additive("1430", "עמילן מעובד(Distarch glycerine)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1440", "עמילן מעובד (Hydroxy propyl starch)", Safety.Safe,"חומר מסמיך, חומר מייצב, חומר מתחלב",""));
		allAdditives.add(new Additive("1441", "עמילן מעובד (Hydroxy propyl distarch glycerine)", Safety.Safe,"חומר מסמיך",""));
		allAdditives.add(new Additive("1442", "עמילן מעובד (Hydroxy propyl distarch phosphate)", Safety.Safe,"חומר מסמיך",""));
		allAdditives.add(new Additive("1443", "עמילן מעובד (Hydroxy propyl distarch glycerol)", Safety.Safe,"",""));
		allAdditives.add(new Additive("1450", "עמילן מעובד (Starch sodium octenyl succinate)", Safety.Safe,"חומר מסמיך, חומר מייצב",""));
		allAdditives.add(new Additive("1451", "עמילן מעובד (Acetylated oxidised starch)", Safety.Safe,"חומר מסמיך",""));
		allAdditives.add(new Additive("1501", "חומצת פחמן בנזליטית", Safety.Safe,"",""));
		allAdditives.add(new Additive("1502", "בוטאן-1, 3-דיאול", Safety.Safe,"",""));
		allAdditives.add(new Additive("1503", "שמן קיק", Safety.Safe,"חומר מגבש",""));
		allAdditives.add(new Additive("1504", "אתיל אצטט", Safety.Safe,"חומר ממס חומרי טעם",""));
		allAdditives.add(new Additive("1505", "ציטרט טריאטיל", Safety.Safe,"חומר מייצב קצף",""));
		allAdditives.add(new Additive("1510", "אתנול", Safety.Safe,"",""));
		allAdditives.add(new Additive("1516", "גליצריל מונואצטט", Safety.Safe,"חומר ממס חומרי טעם",""));
		allAdditives.add(new Additive("1517", "דיאצטין", Safety.Safe,"חומר ממס חומרי טעם",""));
		allAdditives.add(new Additive("1518", "טריאצטין", Safety.Safe,"חומר הלכה",""));
		allAdditives.add(new Additive("1519", "אלכוהול בנזיל", Safety.Safe,"",""));
		allAdditives.add(new Additive("1520", "פרופילן גליקול", Safety.Safe,"חומר הלחה",""));
		allAdditives.add(new Additive("1521", "פוליאתילן גליקול 8000", Safety.Safe,"",""));
		allAdditives.add(new Additive("1525", "הידרוקיתיל צלולוז (Hydroxyethyl cellulose)", Safety.Safe,"חומר מסמיך",""));

	}
	
	
	public ArrayList<Additive> all()
	{
		return allAdditives;
	}
	
	public int findFirstPostion(String eNumber)
	{
		for (int i=0;i<allAdditives.size();i++)
			if (allAdditives.get(i).eNumber.startsWith(eNumber))
				return i;
		return -1;
	}
	
}
